# Generated by Django 4.2.1 on 2023-06-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='edition',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
